### PR TITLE
Allow setting max message size

### LINKED ISSUE #47: issue with specifying settings for gen_
We're running into an issue with gen_smtp thats bouncing emails with max length greater than 10mb. 

Gen_smtp controls this setting here: 
https://github.com/gen-smtp/gen_smtp/blob/master/src/gen_smtp_server_session.erl#L71

However I'm not sure if its configurable in the rabbitmq_email server config block namely because the server_session.erl does not list it as an option:
https://github.com/gen-smtp/gen_smtp/blob/master/src/gen_smtp_server_session.erl#L93

Accompanying gen_smtp documentation seems to confirm this:

```
gen_smtp_server:start(
    smtp_server_example,
    [{sessionoptions, [{allow_bare_newlines, fix},
                       {callbackoptions, [{parse, true}]}]}]).
...
{sessionoptions, gen_smtp_server_session:options()} - see below
...
Session options are:

    {allow_bare_newlines, false | ignore | fix | strip} - see above
    {hostname, inet:hostname()} - which hostname server should send in response to HELO / EHLO commands. Default: inet:gethostname().
    {tls_options, [ssl:server_option()]} - options to pass to ssl:handshake/3 (OTP-21+) / ssl:ssl_accept/3 when STARTTLS command is sent by the client. Only needed if STARTTLS extension is enabled
    {protocol, smtp | lmtp} - when lmtp is passed, the control flow of the [Local Mail Transfer Protocol](https://tools.ietf.org/html/rfc2033) is applied. LMTP is derived from SMTP with just a few variations and is used by standard [Mail Transfer Agents (MTA)](https://en.wikipedia.org/wiki/Message_transfer_agent), like Postfix, Exim and OpenSMTPD to send incoming email to local mail-handling applications that usually don't have a delivery queue. The default value of this option is smtp.
    {callbackoptions, any()} - value will be passed as 4th argument to callback module's init/4
```

Am I missing something obvious here where it's possible to override this setting:
https://github.com/gen-smtp/gen_smtp/blob/fe4f164353d1a08fe0a64200c75fa358abe57b29/src/gen_smtp_server_session.erl#L37

I've tried through the rabbitmq_email server_config block but unsuccessfully
```
	{rabbitmq_email, [
		{server_config, [
			[{port, 2525}, {protocol, tcp}, {domain, "cqvlhbqe001.test.cm.com"},{auth, never}, {tls, never}, {address,{0,0,0,0}}], [{sessionoptions, [{maxsize, 200}]}]
```

I assume I need to merge a change to gen_smtp_server_session.erl to include maxsize as a definable option, correct? that or i need to fork, and build rabbitmq_email with my fork?

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #47

Bump gen_smtp to 1.2.0

cc @a-marcellini @mforde84

### CODE REVIEW

**Comment by lukebakken** [comment]
@a-marcellini you should be able to build from this branch and test the new setting. That would help me out a lot. I have to figure out why the Erlang 23 and 24 test suites won't complete.

**Comment by a-marcellini** [comment]
Thank's @lukebakken! We'll try and report you the outcome.

**Comment by lukebakken** [comment]
@a-marcellini this pull request is complete. Please let me know the outcome of your test or if you have any issues.

**Comment by lukebakken** [comment]
@a-marcellini any update?

**Comment by a-marcellini** [comment]
> @a-marcellini any update?

Hi, I'managed to build and test your update, and I can say that it works like a charm! 
Great job!
The only problem we are experiencing is the multiarch build of the docker image. It thows a segmentation fault for arm arch., problably because of a bug of erlang, that, if we caught it right, they fixed a few days ago:
https://github.com/erlang/otp/pull/6340

**Comment by lukebakken** [comment]
Thank you for testing @a-marcellini

**Comment by lukebakken** [comment]
@mforde84 @a-marcellini - https://github.com/gotthardp/rabbitmq-email/releases/tag/v1.1.0

**Comment by a-marcellini** [comment]
I've found a strange problem with the new release: if I use a client to send an email to rabbit directly it works.
However, if it is a mail server (postfix) that forward the same mail to rabbit, using it as a relay, it doesn't work.
Moreover:
If I use telnet:
```
telnet <rabbitserver> <mailport>
```
The strange answer is:

```
EHLO MyServer
250-mail.local
250-AUTH PLAIN LOGIN
250-SIZE 41943040
250-SIZE 10485760
250-8BITMIME
250-PIPELINING
250 SMTPUTF8
```
Where 41943040 is the message size I put in rabbit.config while 10485760 is the default gen_smtp size, I suppose.

**Comment by lukebakken** [comment]
@a-marcellini please open a new issue with those details:

https://github.com/gotthardp/rabbitmq-email/issues

**Pull request merged**
