### PR TITLE
Do not duplicate SIZE extension

### LINKED ISSUE #55: Duplicated size statement in EHLO
I've found a strange problem with the new release: if I use a client to send an email to rabbit directly it works.
However, if it is a mail server (postfix) that forward the same mail to rabbit, using it as a relay, it doesn't work.
Moreover:
If I use telnet:

`telnet <rabbitserver> <mailport>`
The strange answer is:

```
EHLO MyServer
250-mail.local
250-AUTH PLAIN LOGIN
250-SIZE 41943040
250-SIZE 10485760
250-8BITMIME
250-PIPELINING
250 SMTPUTF8
```
Where 41943040 is the message size I put in rabbit.config while 10485760 is the default gen_smtp size, I suppose.

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #55

### CODE REVIEW

**Comment by lukebakken** [comment]
@a-marcellini - please test this fix in your environment. Thanks a lot!

**Comment by a-marcellini** [comment]
The behaviour has definitely changed:
```
$ telnet localhost 2525
Trying ::1...
Connected to localhost.
Escape character is '^]'.
220 mail.local ESMTP rabbit_email_handler
EHLO COppa
250-mail.local
250-AUTH PLAIN LOGIN
250-SIZE 41943040
250-8BITMIME
250-PIPELINING
250 SMTPUTF8
```

And now postfix delivers the message and rabbit doesn't bounce it back.
```
Oct 20 15:00:41 mailserver postfix-in/qmgr[360]: D8CEE2A4061: from=<address1@mail.local>, size=13760367, nrcpt=1 (queue active)
...
Oct 20 15:00:41 mailserver postfix-in/smtp[490]: D8CEE2A4061: to=<address2@mail.local>, relay=rabbitmq[172.23.0.5]:2525, delay=4.9, delays=4.3/0.02/0.05/0.52, dsn=2.0.0, status=sent (250 015e8da796b65556d8831a0044a25f43)
```

So, it seems it's working!

**Comment by lukebakken** [comment]
@a-marcellini thank you for testing.

**Comment by lukebakken** [comment]
@a-marcellini - https://github.com/gotthardp/rabbitmq-email/releases/tag/v1.1.1

**Pull request merged**
